import Head from 'next/head';
import { useContext } from 'react';

// Context
import { StyleContext } from '../contexts/StyleContext';

// Components
import Themes from '../components/Themes';

export default function Home() {
  const { color, font } = useContext(StyleContext);
  return (
    <div
      className={`grid min-h-screen grid-rows-[1fr_auto] items-center justify-center bg-primary text-tertiary ${color} ${font}`}
    >
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <h1 className='text-3xl text-h1 '>Hello world!</h1>

        <Themes />
      </main>

      <footer className='text-center'>This is footer</footer>
    </div>
  );
}
